#!/bin/bash


RPI="rpi01 rpi02 rpi03 rpi03 rpi04 rpi05 rpi06 rpi07 rpi08 rpi09 rpi10 rpi11 rpi12 rpi13 rpi14 rpi15 rpi16 rpi17 rpi18 rpi19 rpi20 ed"

if [ "$#" -gt 0 ] ; then
	RPI="$@"

fi

for items in  $RPI ; do
	ping "$items" -c 1 &> /dev/null
	if [ $? -eq 0 ] ; then
		echo "$items" : Alive
	else
		echo "$items" : Dead
	fi
done
exit  0
